# Generated by Django 4.1.7 on 2023-10-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_track', '0004_creditdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='salary_date',
            field=models.DateField(default='2023-10-01'),
            preserve_default=False,
        ),
    ]
