# Generated by Django 4.1.7 on 2023-09-28 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userotp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_touch_capable', models.BooleanField(default=False)),
                ('is_pc', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('browser_fam', models.CharField(max_length=50)),
                ('browser_ver', models.CharField(max_length=50)),
                ('os_fam', models.CharField(max_length=50)),
                ('os_ver', models.CharField(max_length=50)),
                ('device_fam', models.CharField(max_length=50)),
                ('device_brand', models.CharField(max_length=50, null=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('signin_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_details',
            },
        ),
    ]
