# Generated by Django 4.1.7 on 2023-09-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_logindetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
