# Generated by Django 4.1.7 on 2023-09-29 07:36

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_pass_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userhoto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_photo', models.ImageField(default='images/employee/user.png', upload_to=accounts.models.upload_pic, validators=[accounts.models.user_img_restriction])),
                ('user', models.OneToOneField(error_messages={'unique': 'Profile Photo already exists. So, Try to Update it.'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_photo',
            },
        ),
    ]
