# Generated by Django 4.1.7 on 2023-09-29 11:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userhoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhoto',
            name='profile_photo',
            field=models.ImageField(default='images/user/user.png', upload_to=accounts.models.upload_pic),
        ),
    ]
