# Generated by Django 4.1.7 on 2023-10-03 10:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userhoto_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhoto',
            name='profile_photo',
            field=models.ImageField(default='images/user/user.png', upload_to=accounts.models.upload_pic, validators=[accounts.models.user_img_restriction]),
        ),
    ]
